const saleItems = [
     {
          "id": "RF-1",
          "breed": "Raw Flower",
          "animal": "R4",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {    
          "id": "RF-12",
          "breed": "Raw Flower",
          "animal": "ACDC",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-3",
          "breed": "Raw Flower",
          "animal": "MW",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-4",
          "breed": "Raw Flower",
          "animal": "DD",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-5",
          "breed": "Raw Flower",
          "animal": "MW/DHDS",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-6",
          "breed": "Raw Flower",
          "animal": "LemD",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-7",
          "breed": "Raw Flower",
          "animal": "Sativa",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-8",
          "breed": "Raw Flower",
          "animal": "Indica",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-9",
          "breed": "Raw Flower",
          "animal": "Cotton candy",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-10",
          "breed": "Raw Flower",
          "animal": "Cheese",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-11",
          "breed": "Raw Flower",
          "animal": "Lilac diesel",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "RF-12",
          "breed": "Raw Flower",
          "animal": "Citral glue",
          "location": "oz",
          "unitsAvailable": "-",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {
          "id": "GM-1",
          "breed": "Gummies",
          "animal": "Sleep CBG",
          "location": "1 oz per pack-packs",
          "unitsAvailable": "12.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {
          "id": "GM-2",
          "breed": "Gummies",
          "animal": "Sleep CBD/ACDC",
          "location": "1 oz per pack-packs",
          "unitsAvailable": "2.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {
          "id": "GM-3",
          "breed": "Gummies",
          "animal": "Sleep Indica",
          "location": "1 oz per pack-packs",
          "unitsAvailable": "2.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {
          "id": "GM-4",
          "breed": "Gummies",
          "animal": "Lift",
          "location": "1 oz per pack-packs",
          "unitsAvailable": "8.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {
          "id": "GM-5",
          "breed": "Gummies",
          "animal": "Recovery",
          "location": "1 oz per pack-packs",
          "unitsAvailable": "2.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {
          "id": "GM-6",
          "breed": "Gummies",
          "animal": "Daytime CBG",
          "location": "1 oz per pack-packs",
          "unitsAvailable": "14.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "CY-1",
          "breed": "Candies",
          "animal": "CBD/CBN",
          "location": "oz",
          "unitsAvailable": "4.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "CY-2",
          "breed": "Candies",
          "animal": "Lemongrass",
          "location": "oz",
          "unitsAvailable": "34.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "CY-3",
          "breed": "Candies",
          "animal": "Watermelon",
          "location": "oz",
          "unitsAvailable": "26.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "CY-4",
          "breed": "Candies",
          "animal": "Woe",
          "location": "oz",
          "unitsAvailable": "34.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "CY-5",
          "breed": "Candies",
          "animal": "CBG",
          "location": "oz",
          "unitsAvailable": "11.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TBO-1",
          "breed": "Tinctures-Base Oil",
          "animal": "Indica glycerin",
          "location": "oz",
          "unitsAvailable": "",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TBO-2",
          "breed": "Tinctures-Base Oil",
          "animal": "Sativa",
          "location": "oz",
          "unitsAvailable": "9.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TBO-3",
          "breed": "Tinctures-Base Oil",
          "animal": "Union custom",
          "location": "oz",
          "unitsAvailable": "11.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TBO-4",
          "breed": "Tinctures-Base Oil",
          "animal": "CBN MCT",
          "location": "oz",
          "unitsAvailable": "2.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TBO-5",
          "breed": "Tinctures-Base Oil",
          "animal": "Chaga",
          "location": "oz",
          "unitsAvailable": "",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-1",
          "breed": "Topicals",
          "animal": "Garden of Bloom",
          "location": "oz",
          "unitsAvailable": "2.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-2",
          "breed": "Topicals",
          "animal": "Garden of Peace",
          "location": "oz",
          "unitsAvailable": "5.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-3",
          "breed": "Topicals",
          "animal": "Lip Lover",
          "location": "oz",
          "unitsAvailable": "50.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-4",
          "breed": "Topicals",
          "animal": "Massage Oil Cream",
          "location": "oz",
          "unitsAvailable": "",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-5",
          "breed": "Topicals",
          "animal": "No 10",
          "location": "oz",
          "unitsAvailable": "2.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-6",
          "breed": "Topicals",
          "animal": "Therapeutic Touch",
          "location": "oz",
          "unitsAvailable": "2.00",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {    "id": "TOP-7",
          "breed": "Topicals",
          "animal": "Soaps",
          "location": "each",
          "unitsAvailable": "12.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-8",
          "breed": "Topicals",
          "animal": "TLC Cream Small",
          "location": "oz",
          "unitsAvailable": "22.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-9",
          "breed": "Topicals",
          "animal": "TLC Cream Large",
          "location": "oz",
          "unitsAvailable": "",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-10",
          "breed": "Topicals",
          "animal": "Bath Balms sm",
          "location": "oz",
          "unitsAvailable": "1.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "TOP-11",
          "breed": "Topicals",
          "animal": "Bath Balms lg",
          "location": "oz",
          "unitsAvailable": "",
          "unitCost": "-",
          "cost": "-",
         "recipe":  false, 
          "image": ""
     },
     {    "id": "MM-1",
          "breed": "Marshmallows",
          "animal": "Indica",
          "location": "each",
          "unitsAvailable": "44.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "MM-2",
          "breed": "Marshmallows",
          "animal": "Sative",
          "location": "each",
          "unitsAvailable": "73.00",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     },
     {    "id": "MM-3",
          "breed": "Marshmallows",
          "animal": "CBG",
          "location": "each",
          "unitsAvailable": "",
          "unitCost": "-",
          "cost": "-",
          "recipe": true,
          "image": ""
     }
]
module.exports = saleItems
